<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>2c98dbca-9da0-49d0-b3a8-4d980e5ce862</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avans.Identity.DapperOrm" Version="1.0.3" />
        <PackageReference Include="Dapper" Version="2.1.72" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0-preview4.26064.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
    </ItemGroup>

</Project>
